[program:claims-postgres]
command=/usr/lib/postgresql/15/bin/postgres -D /app/loreal-claims-engine/.pgdata -c listen_addresses=localhost -p 5432
user=postgres
autostart=true
autorestart=true
priority=5
stderr_logfile=/var/log/supervisor/claims-postgres.err.log
stdout_logfile=/var/log/supervisor/claims-postgres.out.log
stopsignal=INT

[program:claims-api]
command=/usr/bin/yarn start:dev
directory=/app/loreal-claims-engine/backend
autostart=true
autorestart=true
priority=10
stderr_logfile=/var/log/supervisor/claims-api.err.log
stdout_logfile=/var/log/supervisor/claims-api.out.log
stopsignal=TERM
stopasgroup=true
killasgroup=true

[program:claims-web]
command=/usr/bin/yarn dev
directory=/app/loreal-claims-engine/frontend
autostart=true
autorestart=true
priority=10
stderr_logfile=/var/log/supervisor/claims-web.err.log
stdout_logfile=/var/log/supervisor/claims-web.out.log
stopsignal=TERM
stopasgroup=true
killasgroup=true
